### ISSUE TITLE
SCLK signal not as expected for all SPI modes

### ISSUE THREAD

**Issue by eoshea** [schang412/cocotbext-spi#4]
By setting SCLK to NOT CPHA before every word transmission

https://github.com/schang412/cocotbext-spi/blob/0005eb12bdb263f18262724a84e9f2050b44fdfc/cocotbext/spi/spi.py#L170-L171

and always waiting for the 'shifting out' edge first, the SCLK signal expected for SPI modes where the 'sampling' edge comes first is not produced (CPHA=0).

I think the section of code shown below also needs to be changed to allow for the first edge to be a 'sampling' edge (and the appropriate sampling edge for the SPI mode). At the moment (for certain modes) it seems that in order to return SCLK to the expected idle state (governed by CPOL) an additional clock edge must be added at the end of each transmission. Although, this still results in an unconventional SCLK signal.

https://github.com/schang412/cocotbext-spi/blob/0005eb12bdb263f18262724a84e9f2050b44fdfc/cocotbext/spi/spi.py#L181-L197

A potential solution could include something like the following:

```
if self._config.cpol:   # CPOL=1, first edge from 1 -> 0 (falling)
    first_edge = FallingEdge(self._sclk)
    second_edge = RisingEdge(self._sclk)
else:                   # CPOL=0, first edge from 0 -> 1 (rising)
    first_edge = RisingEdge(self._sclk)
    second_edge = FallingEdge(self._sclk)
```

then `await` the `first_edge` and `second_edge` in the 'for' loop mentioned above, and either 'sample' or 'shift out' on those edges appropriately by checking the value of CPHA.  But there are probably better/easier ways to achieve what is needed.

**Comment by schang412** [comment]
Hi, I think the latest commit has resolved this. I had mistakenly assumed that we wanted a shift out on the clock edge. However, as you pointed out, when CPHA=0, this results in an unconventional clock. I have fixed this so that for CPHA=0, we clock the first bit of data out when we bring the chip select low. It also seems that it is conventional that our first action is on the rising edge according to [timing diagrams by Analog Devices](https://www.analog.com/en/analog-dialogue/articles/introduction-to-spi-interface.html). Please let me know if the issue still exists.
